### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [KatieMFritz/tc359-project1#1]
Looking good! A little note for your `app.rb` file: It looks like you're indenting with tabs. It's standard in Ruby to always indent with two spaces. See if you can use Sublime to convert those to spaces for future projects.

**Comment by KatieMFritz** [comment]
![indentation](https://cloud.githubusercontent.com/assets/7085184/5666357/fa2004a0-972c-11e4-81a7-508b02eedf68.PNG)
Is this how I would do that?

**Comment by chrisvfritz** [comment]
Yep. :smile_cat: And if you click on `Spaces: 2`, then you'll be able to check to `Convert Indentation to Spaces` if you're on a file that's still using tabs.
